{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{set-block scope=root variable=subject}{'Digest for %date'|i18n("design/standard/notification",, hash('%date',currentdate()|l10n(datetime)))}{/set-block}
{"This digest email is to inform you of new items:"}
<br/><br/>
{section name=Handlers loop=fetch(notification,digest_handlers,hash(date,$date.timestamp,address,$address))}

{include handler=$Handlers:item date=$date address=$address uri=concat( "design:notification/handler/",$Handlers:item.id_string,"/view/digest_plain.tpl")}

{/section}
<br/><br/>

{"If you do not want to continue receiving these notifications, please edit your profile settings"}


